services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: basith321
      POSTGRES_PASSWORD: root@123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root@123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres

  config-server-ms:
    image: basith321/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      -microservice-network
      -postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: basith321/servicereg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      -microservice-network
      -postgres

  companyms:
    image: basith321/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - config-server-ms
      - rabbitmq
    networks:
      -microservice-network
      -postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: basith321/jobms:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      -microservice-network
      -postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reviewms:
    image: basith321/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - config-server-ms
      - rabbitmq
    networks:
      -microservice-network
      -postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      -EUREKA_CLIENT_SERVICEURL_DEFAULTZOME=http://servicereg:8761/eureka

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres

  gateway-ms:
    image: basith321/gateway-ms:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres
    environments:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin-data: